default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "miaohuang") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>

development:
  <<: *default
  database: pp_development

test:
  <<: *default
  database: pp_test

production:
  <<: *default
  database: pp_production